name: Building + releasing image
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Installing dependencies
        run: sudo apt-get install -y cgpt vboot-kernel-utils curl rar arch-install-scripts

      - name: Cloning git repositories
        run: |
          git clone --depth=1 https://github.com/eupnea-linux/eupneaos-theme.git
          git clone --depth=1 https://chromium.googlesource.com/chromiumos/third_party/linux-firmware

      - name: Create temp directory
        run: mkdir /tmp/eupneaos-build/

      - name: Downloading kernel, modules, headers
        run: |
          curl -L "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/bzImage-stable" -o /tmp/eupneaos-build/bzImage
          curl -L "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/modules-stable.tar.xz" -o /tmp/eupneaos-build/modules.tar.xz
          curl -L "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/headers-stable.tar.xz" -o /tmp/eupneaos-build/headers.tar.xz

      - name: Downloading fedora rootfs
        run: curl -L "https://github.com/eupnea-linux/fedora-rootfs/releases/latest/download/fedora-rootfs-37.tar.xz" -o /tmp/eupneaos-build/rootfs.tar.xz

      - name: Building image
        run: sudo python3 build_image.py

      #      - name: Uploading rar archive as artifact
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: eupneaos.bin.rar
      #          path: ./eupneaos.bin.rar

      #  - name: Splitting tar archive
      #    run: split --verbose -b 1900MB eupneaos.bin.tar.xz eupneaos.split.

      - name: Generating release message
        id: tag
        run: echo "::set-output name=commit_message::$(git log -1 --pretty=format:"%s")"

      - name: Deleting old dev release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-build
          name: Image build - ${{ steps.tag.outputs.commit_message }}
          prerelease: true
          body: |
            This is a development build of EupneaOS. Highly unstable!
            
            1. Download all release files
            ~~2. Combine files into tar: ``cat eupneaos.split.?? > eupneaos.bin.tar.xz``~~
            3. Extract eupneaos.bin.tar.xz
            4. Verify checksum of the image: ``sha256sum -c --ignore-missing eupneaos.sha256``
            5. Flash eupneaos.bin to usb/sd-card
            
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            eupneaos.bin.tar.xz
            eupneaos.sha256
          #  eupneaos.split.*
