name: Building + release depthcharge image
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release-depthcharge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Installing dependencies
        run: sudo apt-get install -y cgpt vboot-kernel-utils curl rar

      - name: Cloning git repositories
        run: |
          git clone --depth=1 https://github.com/eupnea-linux/postinstall-scripts.git
          git clone --depth=1 https://github.com/eupnea-linux/audio-scripts.git
          git clone --depth=1 https://github.com/eupnea-linux/eupnea-os-theme.git
          git clone --depth=1 https://github.com/eupnea-linux/systemd-services.git
          git clone --depth=1 https://chromium.googlesource.com/chromiumos/third_party/linux-firmware

      - name: Create temp directory
        run: mkdir /tmp/eupnea-os-build/

      - name: Downloading kernel, modules, headers
        run: |
          curl -L "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/bzImage-stable" -o /tmp/eupnea-os-build/bzImage
          curl -L "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/modules-stable.tar.xz" -o /tmp/eupnea-os-build/modules.tar.xz
          curl -L "https://github.com/eupnea-linux/mainline-kernel/releases/latest/download/headers-stable.tar.xz" -o /tmp/eupnea-os-build/headers.tar.xz

      - name: Downloading fedora rootfs
        run: curl -L "https://github.com/eupnea-linux/fedora-rootfs/releases/latest/download/fedora-rootfs-37.tar.xz" -o /tmp/eupnea-os-build/rootfs.tar.xz

      - name: Building depthcharge image
        run: sudo python3 build_depthcharge.py

      - name: Splitting tar
        run: split --verbose -b 1900MB eupnea-depthcharge.bin.tar.xz eupnea-depthcharge.split.

      - name: Generating release message
        id: tag
        run: echo "::set-output name=commit_message::$(git log -1 --pretty=format:"%s")"

      - name: Deleting old dev release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-build
          name: Image build - ${{ steps.tag.outputs.commit_message }}
          prerelease: true
          body: |
            This is a development build of Eupnea OS. Highly unstable!
            
            1. Combine images to a tar with: ``cat eupnea-depthcharge.split.?? > eupnea-depthcharge.tar.xz``
            2. Extract tar, flash bin to usb
            
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            eupnea-depthcharge.split.*
