name: Building depthcharge image
on:
  workflow_run:
    workflows:
      - "Preparing for image builds"
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Installing dependencies
        run: sudo apt-get install cgpt vboot-kernel-utils dnf curl -y

      - name: Adding yum repos for dnf
        run: sudo cp configs/yum.repos.d/ /etc/yum.repos.d/

      - name: Cloning repositories
        run: |
          git clone --depth=1 https://github.com/eupnea-linux/postinstall-scripts
          git clone --depth=1 https://github.com/eupnea-linux/audio-scripts
          git clone --depth=1 https://chromium.googlesource.com/chromiumos/third_party/linux-firmware

      - name: Downloading kernel, modules, headers
        run: |
          curl -L "https://github.com/eupnea-linux/kernel/releases/latest/download/bzImage" -o /tmp/eupnea-build/bzImage
          curl -L "https://github.com/eupnea-linux/kernel/releases/latest/download/modules.tar.xz" -o /tmp/eupnea-build/modules.tar.xz
          curl -L "https://github.com/eupnea-linux/kernel/releases/latest/download/headers.tar.xz" -o /tmp/eupnea-build/headers.tar.xz

      - name: Building depthcharge image
        run: python3 build-depthcharge.py

      - name: Uploading image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: stable-kernel
          retention-days: 1
          path: |
            bzImage
            modules.tar.xz
            headers.tar.xz