name: Publish images
on:
  workflow_run:
    workflows: [ "Building depthcharge image", "Building UEFI image" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Generating release tag and setting prerelease + name
        id: tag
        run: |
          if echo $(git log -1 --pretty=format:"%s") | grep -c "stable"
          then
            echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"
            echo "::set-output name=release_type::false"
          else
            echo "::set-output name=release_tag::dev-build" 
            echo "::set-output name=release_type::true"
          fi
          echo "::set-output name=commit_message::$(git log -1 --pretty=format:"%s")"

      - name: creating tmp folder
        run: mkdir /tmp/artifacts

      - name: Download depthcharge artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: build-depthcharge.yml
          workflow_conclusion: completed
          name: eupnea-depthcharge
          path: /tmp/artifacts/

      - name: Download UEFI artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: build-uefi.yml
          workflow_conclusion: completed
          name: eupnea-uefi
          path: /tmp/artifacts/

      - name: Testing
        run: sudo ls -a /tmp/artifacts/

      - name: Publishing new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Image build - ${{ steps.tag.outputs.commit_message }}
          prerelease: ${{ steps.tag.outputs.release_type }}
          body: |
            This is a development build of Eupnea OS. Highly unstable!
            Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            /tmp/artifacts/eupnea-*